=== nzanella/whm/src/data/datagui-1.0.dtd
<!--
   Data GUI version 1.0 DTD

   Namespace = http://whm.sf.net/2004/datagui

   For further information, see: http://whm.sf.net/

   Copyright (c) 2004 Neil Zanella <nzanella at shell dot sf dot net>,
   All Rights Reserved. 

   This DTD module is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//Neil Zanella//DTD Data GUI 1.0//EN"
   SYSTEM "http://whm.sf.net/dtds/datagui/datagui-1.0.dtd"

   $Revision: 1.0 $
   $Date: 2004/08/28 02:24:00 $

Data GUI files allow the programmer to define patterns of behavior which
allow users of data driven graphical user interfaces to interact with
databases in convenient ways. Such behavioral patterns are then
parsed and bound to the application at runtime.

Data GUI files are mainly comprised of behavioral control nodes. These
are abstract entities which are responsible for displaying database
data onto the user interface and ensure the correctness of actions
requested by the user on database data prior to carrying them out.
In order to carry out their task control nodes know about collections
of fields coming from custom queries executed on the database and also
know about user input coming from the user interface in the form of
widgets properties. Control nodes are then able to transform data
and perform all necessary checks as data is passed back and forth
between the user interface and the database.

Each screen may contain widgets pertaining to more than one control
node and conversely a control node may span several screens as control
nodes are completely decoupled from the user interface. Some control
nodes may not display all of their data as some of it may be used to
enforce master detail relationships. These are used to filter data
presented to the user by some control nodes based on data selections
taking place within others. Control nodes assume the existence of
custom defined actions to add, modify, and remove data which the
programmer defines by means of SQL queries to ensure integrity
constraints are satisfied prior to executing them. Furthermore
control nodes may be linked in another way by means of send
receive relationships which allow user input to be filled
out on the basis of user selections on widgets pertaining
to other control nodes. Control nodes may also be cloned.
-->

<!--================ Data GUI ============================================-->

<!ELEMENT datagui ((control | masterdetail | sendreceive | selectorsendreceive)*)>

<!ATTLIST datagui version CDATA #FIXED "1.0">

<!--================ Control =============================================-->

<!ELEMENT control (extractor, selector, manipulator?)>

<!ATTLIST control cname ID #REQUIRED>

<!ELEMENT clonecontrol (cloneextractor?, selector, clonemanipulator?)>

<!ATTLIST control cname ID #REQUIRED srccname ID #REQUIRED>

<!--================ Extractor ===========================================-->

<!ELEMENT extractor (query, field+)>

<!ELEMENT query (#PCDATA)>

<!ELEMENT field EMPTY>

<!ATTLIST field fname CDATA #REQUIRED required (yes|no) "no" type CDATA #REQUIRED>

<!ELEMENT cloneextractor (query)>

<!--================ Selector ============================================-->

<!ELEMENT selector (header+)>

<!ATTLIST selector name ID #REQUIRED>

<!ELEMENT header EMPTY>

<!ATTLIST header fname CDATA #REQUIRED>

<!--================ Manipulator =========================================-->

<!ELEMENT manipulator (exposer+, executor?)>

<!ELEMENT exposer EMPTY>

<!ATTLIST exposer name ID #REQUIRED fname CDATA #REQUIRED>

<!ELEMENT clonemanipulator (exposer+, cloneexecutor?)>

<!--================ Executor ============================================-->

<!ELEMENT executor (add, modify, remove, submit, cancel, inserter, updater, deleter)>

<!ELEMENT cloneexecutor (add, modify, remove, submit, cancel)>

<!ELEMENT add EMPTY>

<!ATTLIST add name ID #REQUIRED>

<!ELEMENT modify EMPTY>

<!ATTLIST modify name ID #REQUIRED>

<!ELEMENT remove EMPTY>

<!ATTLIST remove name ID #REQUIRED>

<!ELEMENT submit EMPTY>

<!ATTLIST submit name ID #REQUIRED>

<!ELEMENT cancel EMPTY>

<!ATTLIST cancel name ID #REQUIRED>

<!ELEMENT inserter (emptytest*, emptycheck*, query*)>

<!ELEMENT updater (emptytest*, emptycheck*, query*)>

<!ELEMENT deleter (emptytest*, emptycheck*, query*)>

<!ELEMENT emptytest (query, emptycase, nonemptycase)>

<!ELEMENT emptycase (emptytest*, emptycheck*, query*)>

<!ELEMENT nonemptycase (emptytest*, emptycheck*, query*)>

<!ELEMENT emptycheck (query, errormessage)>

<!ELEMENT nonemptycheck (query, errormessage)>

<!ELEMENT errormessage (#PCDATA)>

<!--================ Master Detail Relationships =========================-->

<!ELEMENT masterdetail (mdfield+)>

<!ATTLIST masterdetail mcname IDREF #REQUIRED dcname IDREF #REQUIRED>

<!ELEMENT mdfield EMPTY>

<!ATTLIST mdfield fname CDATA #REQUIRED>

<!--================ Send Receive Relationships ==========================-->

<!ELEMENT sendreceive (maplet+, messenger)>

<!ATTLIST sendreceive scname IDREF #REQUIRED rcname IDREF #REQUIRED>

<!ELEMENT maplet EMPTY>

<!ATTLIST maplet sfname CDATA #REQUIRED rfname CDATA #REQUIRED>

<!ELEMENT messenger EMPTY>

<!ATTLIST messenger name CDATA #REQUIRED>

<!--================= Selector Send Receive Relationships ================-->

<!ELEMENT selectorsendreceive (maplet+)>

<!ATTLIST selectorsendreceive ssname IDREF #REQUIRED rsname IDREF #REQUIRED>

<!--======================================================================-->

=== nzanella/whm/src/data/datagui.xml
<?xml version="1.0"?>
<!DOCTYPE datagui PUBLIC "-//Neil Zanella//DTD Data GUI 1.0//EN" "http://whm.sf.net/dtds/datagui/datagui-1.0.dtd">
<datagui version="1.0">
  <!-- Inventory Screen items control node -->
  <control cname="inv_items">
    <extractor>
      <query>
        SELECT ccatid, contnum, ccatdesc, taxcat, taxper,
               supid, supname, brandname, itemcode,
               advsellprice, avsellprice, advpurchprice, avpurchprice,
               numstored + numloose AS numinstock, numstored, numloose, numdamaged, numincoming, numoutgoing
        FROM (TaxCategories NATURAL JOIN Containers NATURAL JOIN ContainerCategories NATURAL JOIN Suppliers)
        NATURAL RIGHT JOIN
        (SELECT supid, brandname, itemcode, advsellprice, advpurchprice,
             avsellprice, avpurchprice, numloose, numdamaged,
             numIncoming, numOutgoing
         FROM (IncomingItemsView
               NATURAL RIGHT JOIN
               (AveragePurchasingPriceView NATURAL RIGHT JOIN Items NATURAL LEFT JOIN AverageSellingPriceView)
               NATURAL LEFT JOIN
               OutgoingItemsView)
        ) IncomingOutgoingItems
      </query>
      <field fname="ccatid" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="contnum" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="ccatdesc" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="taxcat" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="taxper" type="GDA_VALUE_TYPE_NUMERIC"/>
      <field fname="supid" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supname" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="brandname" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="itemcode" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="advsellprice" type="GDA_VALUE_TYPE_NUMERIC"/>
      <field fname="avsellprice" type="GDA_VALUE_TYPE_NUMERIC"/>
      <field fname="advpurchprice" type="GDA_VALUE_TYPE_NUMERIC"/>
      <field fname="avpurchprice" type="GDA_VALUE_TYPE_NUMERIC"/>
      <field fname="numinstock" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="numstored" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="numloose" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="numdamaged" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="numincoming" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="numoutgoing" type="GDA_VALUE_TYPE_INTEGER"/>
    </extractor>
    <selector name="inv_items_clist1">
      <header fname="ccatid"/>
      <header fname="contnum"/>
      <header fname="ccatdesc"/>
      <header fname="taxcat"/>
      <header fname="taxper"/>
      <header fname="supid"/>
      <header fname="supname"/>
      <header fname="brandname"/>
      <header fname="itemcode"/>
      <header fname="advsellprice"/>
      <header fname="avsellprice"/>
      <header fname="advpurchprice"/>
      <header fname="avpurchprice"/>
      <header fname="numinstock"/>
      <header fname="numstored"/>
      <header fname="numloose"/>
      <header fname="numdamaged"/>
      <header fname="numincoming"/>
      <header fname="numoutgoing"/>
    </selector>
  </control>
  <!-- Inventory Screen purchases control node -->
  <control cname="inv_purchases">
    <extractor>
      <query>
        SELECT supid, brandname, itemcode, purchnum, purchdate,
               numpurchased, numpurchsatisfied, numpurchased - numpurchsatisfied AS numpurchpending
        FROM (PurchaseItems NATURAL JOIN Purchases) NATURAL JOIN ReceivePurchasedItems
        WHERE supid = $ctl.inv_items.supid
          AND brandname = $ctl.inv_items.brandname
          AND itemcode = $ctl.inv_items.itemcode
      </query>
      <field fname="purchid" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="purchdate" type="GDA_VALUE_TYPE_DATE"/>
      <field fname="numpurch" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="purchnumsatisfied" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="purchnumpending" type="GDA_VALUE_TYPE_INTEGER"/>
    </extractor>
    <selector name="inv_purchases_clist1">
      <header fname="purchid"/>
      <header fname="purchdate"/>
      <header fname="numpurch"/>
      <header fname="purchnumsatisfied"/>
      <header fname="purchnumpending"/>
    </selector>
  </control>
  <!-- Inventory Screen sales control node -->
  <control cname="inv_sales">
    <extractor>
      <query>
        SELECT supid, brandname, itemcode, salenum, saledate, 
               numsold, numsoldsatisfied, numsold - numsoldsatisfied AS numsoldpending
        FROM (SellItems NATURAL JOIN Sales) NATURAL JOIN SendSoldItems
        WHERE supid = $ctl.inv_items.supid
          AND brandname = $ctl.inv_items.brandname
          AND itemcode = $ctl.inv_items.itemcode
      </query>
      <field fname="salenum" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="saledate" type="GDA_VALUE_TYPE_DATE"/>
      <field fname="numsold" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="salenumsatisfied" type="GDA_VALUE_TYPE_INTEGER"/>
      <field fname="salenumpending" type="GDA_VALUE_TYPE_INTEGER"/>
    </extractor>
    <selector name="inv_sales_clist1">
      <header fname="salenum"/>
      <header fname="saledate"/>
      <header fname="numsold"/>
      <header fname="salenumsatisfied"/>
      <header fname="salenumpending"/>
    </selector>
  </control>
  <!-- Master-Detail Links across Inventory Screen -->
  <masterdetail mcname="inv_items" dcname="inv_sales">
    <mdfield fname="supid"/>
    <mdfield fname="brandname"/>
    <mdfield fname="itemcode"/>
  </masterdetail>
  <masterdetail mcname="inv_items" dcname="inv_purchases">
    <mdfield fname="supid"/>
    <mdfield fname="brandname"/>
    <mdfield fname="itemcode"/>
  </masterdetail>
  <!-- Suppliers Screen control nodes -->
  <control cname="sup_suppliers">
    <extractor>
      <query>
        SELECT supid, supname, supstreet, supcity,
               suppostalcode, supprovince, supcountry,
               supphonenumber, supfaxnumber, supemail,
               supwebsite, supregistrationnumber, suptaxcode,
               supbankaccountnumber, bankid, supother
        FROM Suppliers
        ORDER BY supid, supname, supstreet, supcity
      </query>
      <field fname="supid" required="yes" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supname" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supstreet" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supcity" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="suppostalcode" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supprovince" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supcountry" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supphonenumber" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supfaxnumber" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supemail" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supwebsite" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supregistrationnumber" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="suptaxcode" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supbankaccountnumber" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="bankid" type="GDA_VALUE_TYPE_STRING"/>
      <field fname="supother" type="GDA_VALUE_TYPE_STRING"/>
    </extractor>
    <selector name="sup_suppliers_clist1">
      <header fname="supid"/>
      <header fname="supname"/>
      <header fname="supstreet"/>
      <header fname="supcity"/>
    </selector>
    <manipulator>
      <exposer name="sup_id_entry1" fname="supid"/>
      <exposer name="sup_name_entry1" fname="supname"/>
      <exposer name="sup_street_entry1" fname="supstreet"/>
      <exposer name="sup_city_entry1" fname="supcity"/>
      <exposer name="sup_postalcode_entry1" fname="suppostalcode"/>
      <exposer name="sup_province_entry1" fname="supprovince"/>
      <exposer name="sup_country_entry1" fname="supcountry"/>
      <exposer name="sup_phonenumber_entry1" fname="supphonenumber"/>
      <exposer name="sup_faxnumber_entry1" fname="supfaxnumber"/>
      <exposer name="sup_email_entry1" fname="supemail"/>
      <exposer name="sup_website_entry1" fname="supwebsite"/>
      <exposer name="sup_registrationnumber_entry1" fname="supregistrationnumber"/>
      <exposer name="sup_taxcode_entry1" fname="suptaxcode"/>
      <exposer name="sup_bankaccountnumber_entry1" fname="supbankaccountnumber"/>
      <exposer name="sup_bankid_entry1" fname="bankid"/>
      <exposer name="sup_other_textview1" fname="supother"/>
      <executor>
        <add name="sup_add_togglebutton1"/>
        <modify name="sup_modify_togglebutton1"/>
        <remove name="sup_remove_togglebutton1"/>
        <submit name="sup_submit_togglebutton1"/>
        <cancel name="sup_cancel_togglebutton1"/>
        <inserter>
          <!-- ensure primary key uniqueness -->
          <emptycheck>
            <query>
              SELECT supid FROM Suppliers
              WHERE supid = $new.supid
            </query>
            <errormessage>supplier with specified supplier ID already exists!</errormessage>
          </emptycheck>
          <!-- ensure foreign key constraint is met -->
          <emptytest>
            <query>
              SELECT NULL WHERE $new.bankid = $new.bankid
            </query>
            <nonemptycase>
              <nonemptycheck>
                <query>
                  SELECT bankid FROM Banks
                  WHERE bankid = $new.bankid
                </query>
                <errormessage>bank with specified bank ID does not exist!</errormessage>
              </nonemptycheck>
            </nonemptycase>
          </emptytest>
          <!-- insert supplier data -->
          <query>
            INSERT INTO Suppliers
              (supid, supname, supstreet, supcity,
               suppostalcode, supprovince, supcountry,
               supphonenumber, supfaxnumber, supemail,
               supwebsite, supregistrationnumber, suptaxcode,
               supbankaccountnumber, bankid, supother)
            VALUES
              ($new.supid, $new.supname, $new.supstreet, $new.supcity,
